language: node_js
services:
    - rabbitmq
node_js:
    - 6
env:
    - AMQP="amqp://127.0.0.1:5672"
sudo: false
before_script: npm i istanbul mocha typescript@next -g
script: npm install; npm test
after_script: npm run coverage && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
